# .travis.yml
#
# This source file is part of the SDG open source projects.
#
# Copyright ©2016–2017 Jeremy David Giesbrecht and the SDG contributors.
#
# Soli Deo gloria
#
# Licensed under the Apache License, Version 2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!
# THIS IS A SHARED FILE FROM THE REPOSITORY AT https://github.com/SDGGiesbrecht/SDG.
# CHANGES MUST BE MADE THERE.
# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!

language: generic
matrix:
  include:
    - os: osx
    - os: linux
      env: SWIFT_VERSION=3.0
sudo: required
osx_image: xcode8.2
dist: trusty
script: "bash ./Validate\\\ Changes.command --travis"