# .travis.yml
#
# This source file is part of the SDG open source projects.
#
# Copyright ©2016–2017 Jeremy David Giesbrecht and the SDG contributors.
#
# Soli Deo gloria
#
# Licensed under the Apache License, Version 2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!
# This file is managed by Workspace.
# Manual changes will not persist.
# For more information, see:
# https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Continuous Integration.md
# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!

language: generic
matrix:
  include:
    - os: osx
      env:
        - JOB="macOS"
      osx_image: xcode8.2
      script:
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: linux
      dist: trusty
      env:
        - JOB="Linux"
        - SWIFT_VERSION=3.0.2
      script:
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: osx
      env:
        - JOB="iOS"
      osx_image: xcode8.2
      language: objective-c
      xcode_sdk: iphonesimulator
      script:
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: osx
      env:
        - JOB="watchOS"
      osx_image: xcode8.2
      language: objective-c
      xcode_sdk: watchsimulator
      script:
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: osx
      env:
        - JOB="tvOS"
      osx_image: xcode8.2
      language: objective-c
      xcode_sdk: appletvsimulator
      script:
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: linux
      dist: trusty
      env:
        - JOB="Misc."
        - SWIFT_VERSION=3.0.2
      script:
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
